// Signed AWS calls from the edge runtime.
//
// The platform holds one set of its own credentials and never sees a
// customer's. To read a customer's cost data it assumes a role *they* create
// in *their* account, which they can revoke at any time without involving us.
import { AwsClient } from "aws4fetch";

const PLATFORM_REGION = "us-east-1"; // Cost Explorer and Cost Optimization Hub are global, homed here

export function platformCredentials() {
  const accessKeyId = process.env.FINOPS_AWS_ACCESS_KEY_ID;
  const secretAccessKey = process.env.FINOPS_AWS_SECRET_ACCESS_KEY;
  const accountId = process.env.FINOPS_AWS_ACCOUNT_ID;
  if (!accessKeyId || !secretAccessKey || !accountId) return null;
  return { accessKeyId, secretAccessKey, accountId };
}

// AWS explicitly requires the external ID to be generated by the platform and
// to differ per customer: reusing one across customers reintroduces exactly the
// confused-deputy problem it exists to prevent.
export function newExternalId() {
  const bytes = crypto.getRandomValues(new Uint8Array(24));
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

class AwsError extends Error {
  constructor(message, { code, status } = {}) {
    super(message);
    this.code = code;
    this.status = status;
  }
}
export { AwsError };

// STS speaks the older query protocol rather than JSON.
export async function assumeRole({ roleArn, externalId, sessionName = "finops-read" }) {
  const platform = platformCredentials();
  if (!platform) throw new AwsError("Platform AWS credentials are not configured", { code: "NoPlatformCreds" });

  const client = new AwsClient({
    accessKeyId: platform.accessKeyId,
    secretAccessKey: platform.secretAccessKey,
    service: "sts",
    region: PLATFORM_REGION,
  });

  const params = new URLSearchParams({
    Action: "AssumeRole",
    Version: "2011-06-15",
    RoleArn: roleArn,
    RoleSessionName: sessionName,
    DurationSeconds: "900", // shortest STS allows; we only need one burst of reads
  });
  // Omitted entirely when absent, so the "does this role work WITHOUT the
  // external ID?" probe is a genuine test rather than a differently-shaped one.
  if (externalId) params.set("ExternalId", externalId);

  const res = await client.fetch("https://sts.amazonaws.com/", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: params.toString(),
  });

  const text = await res.text();
  if (!res.ok) {
    const code = /<Code>([^<]+)<\/Code>/.exec(text)?.[1] || "AssumeRoleFailed";
    const message = /<Message>([^<]+)<\/Message>/.exec(text)?.[1] || "Could not assume the role";
    throw new AwsError(message, { code, status: res.status });
  }

  const pick = (tag) => new RegExp(`<${tag}>([^<]+)</${tag}>`).exec(text)?.[1];
  const accessKeyId = pick("AccessKeyId");
  const secretAccessKey = pick("SecretAccessKey");
  const sessionToken = pick("SessionToken");
  if (!accessKeyId || !secretAccessKey || !sessionToken) {
    throw new AwsError("STS returned an unreadable response", { code: "BadStsResponse" });
  }
  return { accessKeyId, secretAccessKey, sessionToken };
}

// Cost Explorer and Cost Optimization Hub are both AWS-JSON services.
export async function awsJson({ creds, service, target, body, region = PLATFORM_REGION }) {
  const client = new AwsClient({ ...creds, service, region });
  const host = `${service}.${region}.amazonaws.com`;
  const res = await client.fetch(`https://${host}/`, {
    method: "POST",
    headers: { "content-type": "application/x-amz-json-1.1", "x-amz-target": target },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let parsed = null;
  try { parsed = text ? JSON.parse(text) : null; } catch { /* fall through to raw text */ }
  if (!res.ok) {
    const code = (parsed?.__type || "").split("#").pop() || "AwsRequestFailed";
    throw new AwsError(parsed?.message || parsed?.Message || text.slice(0, 300) || "AWS request failed", {
      code,
      status: res.status,
    });
  }
  return parsed;
}

export const ce = (creds, operation, body) =>
  awsJson({ creds, service: "ce", target: `AWSInsightsIndexService.${operation}`, body });

export const coh = (creds, operation, body) =>
  awsJson({ creds, service: "cost-optimization-hub", target: `CostOptimizationHub.${operation}`, body });
