-- Multi-tenant storage for customers' AWS connections.
--
-- The security model leans on row-level security rather than on application
-- code: every read and write is filtered by auth.uid(), so one customer cannot
-- reach another's connection even if a handler forgets to filter. The API talks
-- to PostgREST with the caller's own access token for exactly this reason —
-- there is no service-role key in the edge runtime that could bypass RLS.

create table if not exists public.finops_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,

  -- Generated by us, never by the customer, and unique per connection: AWS is
  -- explicit that a third party reusing one external ID across customers
  -- reintroduces the confused-deputy problem it exists to prevent.
  external_id text not null unique,

  -- Null until the customer has created the role and we have verified it.
  role_arn text,
  aws_account_id text,
  label text,

  status text not null default 'pending'
    check (status in ('pending', 'active')),

  created_at timestamptz not null default now(),
  verified_at timestamptz,
  last_used_at timestamptz,

  -- A row cannot claim to be usable without the role it is supposed to use.
  constraint active_rows_have_a_role
    check (status = 'pending' or role_arn is not null)
);

create index if not exists finops_connections_user_idx
  on public.finops_connections (user_id, created_at desc);

-- One customer should not be able to point two of their own connections at the
-- same role, which would double-count spend across the account list.
create unique index if not exists finops_connections_user_role_idx
  on public.finops_connections (user_id, role_arn)
  where role_arn is not null;

alter table public.finops_connections enable row level security;

-- Four explicit policies rather than one permissive "for all": it keeps the
-- intent readable, and means a mistake in one verb cannot widen the others.
create policy "read own connections"
  on public.finops_connections for select
  to authenticated
  using (auth.uid() = user_id);

create policy "create own connections"
  on public.finops_connections for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "update own connections"
  on public.finops_connections for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "delete own connections"
  on public.finops_connections for delete
  to authenticated
  using (auth.uid() = user_id);
